pipeline:
  confidence_threshold: 0.5

data:
  test_json: "./data/test.json"
  image_dir: "./data/images/"

evaluation:
  iou_threshold: 0.5 # AP50 - IoU

small_model:
  name: "small_model_dummy" # checkpoint: "small_model/weights/best.pth"

large_model:
  name: "large_model_dummy" # checkpoint: "large_model/weights/best.pth"
